version: '3.5'
services:
######################################################
# AIRFLOW
######################################################

  airflow:
    build: ./
    restart: always
    container_name: airflow_clean
    env_file: 
      # copy example file user_variables.env 
      - ./user_variables.env
    volumes:
      - ./custom_modules:/usr/local/airflow/custom_modules
      #- ./airflow.cfg:/usr/local/airflow/airflow.cfg
      - ./dags:/usr/local/airflow/dags
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8080" ]
      timeout: 45s
      interval: 10s
      retries: 10